stages:
  - prepare
  - test
  - release

default:
  image: node:18.16.0
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-8 --activate
    - pnpm config set store-dir .pnpm-store
    - SHELL="$(which bash)" pnpm setup
  cache: &cache
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store

install-dependencies:
  stage: prepare
  interruptible: true
  if: $CI_COMMIT_BRANCH == 'main'
  cache:
    <<: *cache
    policy: push
  script:
    - pnpm install
    - npx semantic-release@21

test-e2e:
  stage: test
  interruptible: true
  image: mcr.microsoft.com/playwright:v1.35.0-jammy
  when: on_success
  parallel: 7
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-8 --activate
    - pnpm config set store-dir .pnpm-store
    - SHELL="$(which bash)" pnpm setup
  script:
    - pnpm install
    - npx playwright install --with-deps
    - npx playwright test
  artifacts:
    when: always
    paths:
      - playwright-report/
      - test-results/
      - results.xml
    reports:
      junit: results.xml
    expire_in: 1 week

release:
  stage: release
  needs: ['test']
  if: $CI_COMMIT_BRANCH == 'main'
  script:
    - pnpm run semantic-release
