stages:
  - prepare
  - deploy
  - release

default:
  image: node:18.16.0
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-8 --activate
    - pnpm config set store-dir .pnpm-store
  cache: &cache
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store

install-dependencies:
  stage: prepare
  interruptible: true
  cache:
    <<: *cache
    policy: push
  script:
    - pnpm install
    - npx semantic-release@21

deploy-preview:
  stage: deploy
  except:
    - main
  script:
    - pnpm add --global vercel
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - vercel build --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt  --token=$VERCEL_TOKEN

deploy-production:
  stage: deploy
  only:
    - main
  script:
    - pnpm add --global vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN

release:
  stage: release
  needs: ['deploy-production']
  only:
    - main
  script:
    - pnpm run semantic-release
