stages:
  - test
  - release

.install:
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-8 --activate
    - pnpm config set store-dir .pnpm-store
    - SHELL="$(which bash)" pnpm setup

test-e2e:
  stage: test
  interruptible: true
  image: mcr.microsoft.com/playwright:v1.35.1-jammy
  parallel: 7
  extends: .install
  script:
    - CI=true pnpm i
    - CI=true pnpm playwright install
    - CI=true pnpm playwright test --shard=$CI_NODE_INDEX/$CI_NODE_TOTAL
  artifacts:
    when: always
    paths:
      - playwright-report/
      - test-results/
      - results.xml
    reports:
      junit: results.xml
    expire_in: 1 week

release:
  stage: release
  interruptible: true
  extends: .install
  cache:
    policy: push
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
  script:
    - CI=true pnpm i
    - pnpm semantic-release@21
    - pnpm run semantic-release
