export const DISPLAY_CATEGORY = {
  'All Products': 1,
  'Auto-Sip': 46,
  'Cellar Sweep': 41,
  'Circle Exclusives': 33,
  Coffee: 54,
  'Gift Cards': 21,
  'Gift Sets': 37,
  Giftables: 26,
  'Hide From Site': 53,
  Red: 2,
  Rosé: 28,
  Sale: 42,
  'Scout Circle': 49,
  Sparkling: 27,
  White: 3,
  Wine: 16,
  'Wine Clubs': 5,
}
