export const GROUND_SHIPPING_SHIPPING_METHOD_ID = 1
export const LOCAL_PICK_UP_SHIPPING_METHOD_ID = 6
export const ABC_STORE_SHIPPING_METHOD_ID = 13
export const CORPORATE_GIFTING_SHIPPING_METHOD_ID = 23

export const PICK_UP_SHIPPING_METHOD_IDS = [
  ABC_STORE_SHIPPING_METHOD_ID,
  LOCAL_PICK_UP_SHIPPING_METHOD_ID,
]
