import { Inter, Montserrat } from '@next/font/google'
import { NextPage } from 'next'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })
const montserrat = Montserrat({ subsets: ['latin'], variable: '--font-montserrat' })

const Home: NextPage = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta content="Generated by create next app" name="description" />
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <link href="/favicon.ico" rel="icon" />
    </Head>
    <main className={`${inter.variable} ${montserrat.variable} h-screen`}>
      {/* <p>
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Hic illum ex a incidunt sapiente
        non, minus iure? Fuga suscipit hic labore explicabo quos tempore autem, vel qui, libero in
        fugiat?
      </p> */}
    </main>
  </>
)

export default Home
