import { ChevronRightIcon } from '@heroicons/react/20/solid'
import { GetStaticPropsContext, InferGetStaticPropsType, NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

import { camelizeSnakeKeys } from '@/core/utils'
import { WINE_PAGE_PATH } from '@/lib/paths'
import { createClient } from 'prismic-io'
import { HomePageDocument } from 'types.generated'

type PageProps = InferGetStaticPropsType<typeof getStaticProps>

export const getStaticProps = async ({ previewData }: GetStaticPropsContext) => {
  const client = createClient({ previewData })
  const page = await client.getByUID<HomePageDocument>('home_page', 'home')

  return {
    props: {
      page: camelizeSnakeKeys<HomePageDocument>(page),
    },
  }
}

const HomePage: NextPage<PageProps> = () => (
  <>
    <Head>
      <title>Scout & Cellar | Clean-Crafted Commitment</title>
      <meta content="Generated by create next app" name="description" />
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <link href="/favicon.ico" rel="icon" />
    </Head>
    <main>
      <div className="">
        <div className="flex h-[80vh] w-full items-center justify-center bg-neutral-900/50 bg-[url('/vineyard-bg.jpg')] bg-scroll bg-center lg:bg-fixed">
          <div className="container mx-auto py-8 text-neutral-100 lg:py-32">
            <div className="flex flex-col items-center justify-center gap-6 text-center tracking-wider lg:items-start lg:gap-8 lg:text-left">
              <div>
                <h1 className="lg:mb-8">Live Clean-Crafted.</h1>
                <h2 className="text-4xl font-semibold leading-tight">
                  <span className="block">Better for you.</span>
                  <span className="block">Better for the planet.</span>
                </h2>
              </div>
              <div className="flex flex-col gap-4">
                <Link
                  aria-label="Buy Clean-Crafted Wine"
                  className="flex max-w-full items-center justify-center"
                  href={WINE_PAGE_PATH}
                  role="button"
                >
                  <div
                    className={`
                      flex h-6 max-w-full items-center justify-center gap-2 rounded-lg border-2
                      border-primary-500 bg-primary-500 px-9 py-7 font-semibold
                      tracking-wide text-neutral-50 transition-all
                      hover:border-primary-700 hover:bg-primary-700 lg:h-12
                  `}
                  >
                    Buy Clean-Crafted Wine
                    <ChevronRightIcon className="h-6 w-6" />
                  </div>
                </Link>

                <Link
                  aria-label="Discover the Clean-Crafted Commitment"
                  className="w-fit text-neutral-100 hover:underline"
                  href="/clean-crafted"
                  role="button"
                >
                  What is Clean-Crafted?
                </Link>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  </>
)

export default HomePage
