/** Morgan Address ID from Flight. */
export const MORGAN_ADDRESS_ID = 5985090

/** Morgan Pick Up Address. */
export const MORGAN_ADDRESS = {
  AddressID: MORGAN_ADDRESS_ID,
  FirstName: '',
  LastName: '',
  NickName: '',
  Company: '',
  City: 'Dallas',
  ProvinceID: '48',
  CountryName: 'United States',
  PostalCode: '75234',
  ProvinceAbbreviation: 'TX',
  ProvinceName: 'Texas',
  Street1: '2261 Morgan Parkway',
  Street2: 'STE 180',
  Primary: false,
  Residential: false,
}

// {
//   "PersonID": 679912,
//   "PersonDisplayID": "C649281",
//   "PersonTypeID": 0,
//   "DisplayPostalCode": true,
//   "DisplayStreet3": false,
//   "DisplayStreet4": false,
//   "DisplayRegion": false,
//   "DisplayDeliveryOffice": true,
//   "DisplayLastName2": false,
//   "SelectedOnOrder": null,
//   "AddressID": 7289638,
//   "FirstName": "Haider",
//   "MiddleName": null,
//   "LastName": "Saleem",
//   "LastName2": null,
//   "Company": "",
//   "NickName": "",
//   "City": "Dallas",
//   "DisplayName": null,
//   "CountryID": 1,
//   "CountryName": "United States",
//   "CountryTwoLetterISO": "US",
//   "CountryThreeLetterCode": null,
//   "PhoneNumberFormat": "###-###-####",
//   "ProvinceID": 48,
//   "County": "",
//   "PostalCode": "75234",
//   "ProvinceAbbreviation": "TX",
//   "ProvinceName": "Texas",
//   "Street1": "2261 Morgan Parkway",
//   "Street2": "STE 180",
//   "Street3": "{\"H\":\"1\",\"T\":\"SC\"}",
//   "Street4": "",
//   "Region": "",
//   "DeliveryOffice": null,
//   "Residential": false,
//   "IsValid": true,
//   "Primary": true,
//   "Mailing": true,
//   "IsNexus": false,
//   "CustomFields": [],
//   "FriendlyDescription": "Haider Saleem - 2261 Morgan Parkway, STE 180, {\"H\":\"1\",\"T\":\"SC\"}, Dallas TX 75234",
//   "PhoneNumber": null,
//   "SpecialInstructions": null
// }
