import { useMemo } from 'react'

import { dehydrate, QueryClient } from '@tanstack/react-query'
import { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'

import { ProductListing } from '@/components/product-listing'
import { HOME_PAGE_PATH, WINE_PAGE_PATH } from '@/lib/paths'
import { getWineProducts, PRODUCTS_QUERY_KEY, useProductsQuery } from '@/lib/queries/products'
import { Breadcrumb } from '@/ui/breadcrumb'

export const getStaticProps: GetStaticProps = async () => {
  const queryClient = new QueryClient()
  await queryClient.prefetchQuery(PRODUCTS_QUERY_KEY, getWineProducts)

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  }
}

const WinePage: NextPage = () => {
  const { data: productData, isLoading } = useProductsQuery()

  const products = useMemo(
    () =>
      productData?.filter(
        item =>
          item.categoriesIDs?.includes(1) &&
          item.catalogID === 1 &&
          item.quantityAvailable &&
          item.quantityAvailable > 20
      ),
    [productData]
  )

  if (isLoading) {
    return <>Loading...</>
  }

  return (
    <>
      <Head>
        <title>Wine | Scout & Cellar | Clean-Crafted Commitment</title>
        <meta content="Generated by create next app" name="description" />
      </Head>
      <main className="bg-neutral-50">
        <div className="container my-12 mx-auto">
          <Breadcrumb
            items={[
              { location: HOME_PAGE_PATH, name: 'Home' },
              { location: WINE_PAGE_PATH, name: 'Wine' },
            ]}
          />
          {products !== undefined && <ProductListing products={products} />}
        </div>
      </main>
    </>
  )
}

export default WinePage
